{% set cuda_version='.'.join(environ.get('CUDA_VERSION', '9.2').split('.')[:2]) %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set py_version=environ.get('CONDA_PY', 36) %}
{% set rapids_build_version=environ.get('RAPIDS_BUILD_VERSION', '0.10') %}

package:
    name: libbsql-engine
    version: {{ version }}

build:
    number: {{ git_revision_count }}
    string: cuda{{ cuda_version + '_' + git_revision_count }}
    script_env:
      - CUDA_VERSION
      - CUDACXX

source:
    path: ../../..

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cudatoolkit {{ cuda_version }}.*
        - bsql-io {{ version }}.*
        - bsql-comms {{ version }}.*
        - libcudf {{ rapids_build_version }}.*
        - libnvstrings {{ rapids_build_version }}.*
        - librmm {{ rapids_build_version }}.*
        - libhdfs3
        - cmake
    host:
        - cudatoolkit {{ cuda_version }}.*
    run:
        - cudatoolkit {{ cuda_version }}.*
        - bsql-io  {{ version }}.*
        - bsql-comms {{ version }}.*
        - libcudf {{ rapids_build_version }}.*
        - libnvstrings {{ rapids_build_version }}.*
        - librmm {{ rapids_build_version }}.*
        - libhdfs3

about:
    home: http://www.blazingsql.com/
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
