{% set cuda_version='.'.join(environ.get('CUDA_VERSION', '9.2').split('.')[:2]) %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set py_version=environ.get('CONDA_PY', 36) %}

package:
    name: blazingsql-dev
    version: {{ version }}

build:
    number: {{ git_revision_count }}
    string: cuda{{ cuda_version + '_py' + py_version + '_' + git_revision_count }}

source:
    path: ../../../

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - python
        - pip
        - gtest
        - gmock
        - cmake
        - librmm
        - libcudf
        - libnvstrings
        - libhdfs3
        - openssl
        - arrow-cpp =0.14.1
        - cmake
        - maven
        - cppzmq
        - cudatoolkit {{ cuda_version }}.*
        #- blazingsql-toolchain  {{ version }}.*
    run:
        - python
        - pip
        - gtest
        - gmock
        - cmake
        - librmm
        - libcudf
        - libnvstrings
        - libhdfs3
        - openssl
        - arrow-cpp =0.14.1
        - cmake
        - maven
        - cppzmq
        - cudatoolkit {{ cuda_version }}.*
        #- blazingsql-toolchain  {{ version }}.*
about:
    home: http://www.blazingsql.com/
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
