package:
    name: blazingsq-dev
    version: 0.4.0

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - python >=3.6.0
        - blazingsql-ral
        - blazingsql-protocol
        - blazingsql-orchestrator
        - blazingsql-communication
        - blazingsql-io
        - blazingsql-calcite

    run:
        - python >=3.6.0
        - blazingsql-ral
        - blazingsql-protocol
        - blazingsql-orchestrator
        - blazingsql-communication
        - blazingsql-io
        - blazingsql-calcite
about:
    home: http://www.blazingsql.com/
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
