{% set cuda_version='.'.join(environ.get('CUDA_VERSION', '9.2').split('.')[:2]) %}

package:
    name: blazingsq-dev
    version: 0.4.0

source:
    path: ../../../

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - python
        - blazingsql-ral
        - blazingsql-protocol
        - blazingsql-orchestrator
        - blazingsql-communication
        - blazingsql-io
        - blazingsql-calcite

    run:
        - python
        - blazingsql-ral
        - blazingsql-protocol
        - blazingsql-orchestrator
        - blazingsql-communication
        - blazingsql-io
        - blazingsql-calcite
about:
    home: http://www.blazingsql.com/
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
