{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}

package:
    name: bsql-io
    version: {{ version }}

source:
    path: ../../..

build:
    number: {{ git_revision_count }}
    string: {{ git_revision_count }}

requirements:
    build:
        - gtest
        - gmock
        - arrow-cpp=0.15.0
        - cmake
        - bsql-toolchain  {{ version }}.*
    run:
        - arrow-cpp=0.15.0
        - bsql-toolchain  {{ version }}.*

about:
    home: http://www.blazingsql.com/
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
